apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tripinsights
namePrefix: dev-
resources:
  - namespace.yaml
  - ../base
patchesStrategicMerge:
  - poi-patch.yaml
  - trips-patch.yaml
