apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environemnt: dev

---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
spec:
  type: LoadBalancer