name: Trips Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/trips/**'
      - '!src/trips/tests/**'
  workflow_dispatch:
  
env:
  REGISTRY: 'nobeliumcr.azurecr.io'
  IMGREPO: 'tripinsights'
  IMGNAME: 'trips'
  
jobs:

  build-push-trips:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_NOBELIUM_CLIENT_ID }}
        password: ${{ secrets.ACR_NOBELIUM_CLIENT_SECRET }}
          
    - name: Build the Docker image
      working-directory: src/trips
      run: |
        docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMGREPO }}/${{ env.IMGNAME }}:${{ github.run_number }}
        docker push ${{ env.REGISTRY }}/${{ env.IMGREPO }}/${{ env.IMGNAME }}:${{ github.run_number }}
